/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary */
        get: operations["glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/brapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Brapi
         * @description Diagnóstico da conexão com a brapi (status HTTP, token presente, resposta crua).
         *
         *     NÃO expõe o token — só o tamanho. Disponível apenas com DEBUG=true (404 caso contrário),
         *     para não vazar configuração em produção.
         */
        get: operations["debug_brapi_api_debug_brapi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategies */
        get: operations["strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe */
        get: operations["universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asset
         * @description Detalhe completo do ativo: classe+setor canônicos, fundamentos (incl. LPA/VPA),
         *     histórico de proventos e a pontuação explicada (métricas, reasons, red flags, selo de risco).
         */
        get: operations["asset_api_asset__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan Latest
         * @description Último plano gerado (persistido) — para a PlanPage restaurar ao montar.
         */
        get: operations["plan_latest_api_plan_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan History
         * @description Planos anteriores (resumo): quando, quanto, qual estratégia, nº de sugestões.
         */
        get: operations["plan_history_api_plan_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_preferences_get"];
        /** Put Preferences */
        put: operations["put_preferences_api_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_api_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_api_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Watchlist
         * @description Marca/desmarca favorito (⭐). Tipos com favoritos têm o plano restrito a eles.
         */
        patch: operations["patch_watchlist_api_watchlist__ticker__patch"];
        trace?: never;
    };
    "/api/watchlist/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watchlist Radar
         * @description Radar de zona de compra: preço, DY e situação vs preço-teto de Bazin de TODOS os
         *     ativos observados — a watchlist deixa de ser lista inerte e responde 'é hora de
         *     comprar?' sem abrir ativo por ativo. Ordenado pela margem sobre o teto.
         */
        get: operations["watchlist_radar_api_watchlist_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income
         * @description Renda passiva atual estimada da carteira (Σ valor × DY) + Yield on Cost por ativo.
         */
        get: operations["income_api_income_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income Snapshots
         * @description Série mensal registrada da carteira (patrimônio, renda, YoC) — bola de neve real.
         */
        get: operations["income_snapshots_api_income_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/yoc/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yoc History
         * @description Histórico mensal do Yield on Cost de um ativo (dos snapshots).
         */
        get: operations["yoc_history_api_income_yoc__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Projection
         * @description Projeção bola de neve (e, opcionalmente, o aporte necessário para uma renda-alvo).
         */
        post: operations["projection_api_income_projection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income Goal
         * @description Objetivo de renda: combina a renda ATUAL real, a meta persistida e o aporte para dizer
         *     o gap, o % atingido, quanto aportar/mês e em quantos anos você chega lá (Aportador).
         */
        get: operations["income_goal_api_income_goal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/realized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income Realized
         * @description Renda REALIZADA mês a mês — os dividendos que de fato caíram na conta, lidos das
         *     atividades do Ghostfolio (você já os registra lá; nada precisa ser redigitado).
         */
        get: operations["income_realized_api_income_realized_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/announced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income Announced
         * @description Proventos JÁ ANUNCIADOS dos ativos da carteira: 'BBAS3 paga R$ 0,45 dia 12/08 →
         *     você recebe R$ 213'. Agenda real (data-com e pagamento conhecidos), não estimativa.
         */
        get: operations["income_announced_api_income_announced_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income Calendar
         * @description Mapa de proventos mês a mês da carteira atual (estimativa sazonal dos últimos anos).
         */
        get: operations["income_calendar_api_income_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixed Income Summary */
        get: operations["fixed_income_summary_api_fixed_income_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Account */
        post: operations["create_account_api_fixed_income_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive Account */
        delete: operations["archive_account_api_fixed_income_accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_fixed_income_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/fixed-income/accounts/{account_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_fixed_income_accounts__account_id__entries_get"];
        put?: never;
        /** Add Entry */
        post: operations["add_entry_api_fixed_income_accounts__account_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/accounts/{account_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_api_fixed_income_accounts__account_id__entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Order */
        delete: operations["delete_order_api_orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountIn */
        AccountIn: {
            /**
             * Name
             * @description Ex.: 'CDB Banco X', 'Tesouro Selic 2029', 'Conta'.
             */
            name: string;
            /** Institution */
            institution?: string | null;
            /**
             * Kind
             * @description 'cdb'|'tesouro'|'poupanca'|'conta'|'outro'.
             */
            kind?: string | null;
            /**
             * Benchmark
             * @description 'cdi'|'selic'|'prefixado'|'ipca' (informativo).
             */
            benchmark?: string | null;
        };
        /**
         * AccountPatch
         * @description PATCH parcial da conta: só os campos enviados mudam. `archived=False` desarquiva —
         *     arquivar deixou de ser sem-volta na UI.
         */
        AccountPatch: {
            /** Name */
            name?: string | null;
            /** Institution */
            institution?: string | null;
            /** Kind */
            kind?: string | null;
            /** Benchmark */
            benchmark?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** AccountSummary */
        AccountSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Institution */
            institution?: string | null;
            /** Kind */
            kind?: string | null;
            /** Benchmark */
            benchmark?: string | null;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Current Balance
             * @default 0
             */
            current_balance: number;
            /**
             * Last Yield Annual
             * @description Rendimento anualizado (fração).
             */
            last_yield_annual?: number | null;
            /**
             * Last Yield Gain
             * @description Ganho do período (BRL).
             */
            last_yield_gain?: number | null;
            /** Last Yield From */
            last_yield_from?: string | null;
            /** Last Yield To */
            last_yield_to?: string | null;
            /** Last Yield Business Days */
            last_yield_business_days?: number | null;
            /**
             * Pct Of Cdi
             * @description Rendimento como fração do CDI (1.0 = 100%).
             */
            pct_of_cdi?: number | null;
        };
        /** Allocations */
        Allocations: {
            /**
             * By Class
             * @description Peso por classe (0..1).
             */
            by_class?: {
                [key: string]: number;
            };
            /**
             * By Sector
             * @description Peso por setor (0..1).
             */
            by_sector?: {
                [key: string]: number;
            };
        };
        /** AnnouncedPayment */
        AnnouncedPayment: {
            /** Ticker */
            ticker: string;
            /**
             * Payment Date
             * @description Data de pagamento (None = anunciado, a definir).
             */
            payment_date?: string | null;
            /** Ex Date */
            ex_date?: string | null;
            /** Value Per Share */
            value_per_share: number;
            /** Net Value Per Share */
            net_value_per_share: number;
            /** Type */
            type?: string | null;
            /**
             * Quantity
             * @description Cotas na carteira.
             */
            quantity?: number | null;
            /**
             * Total Net
             * @description R$ líquidos a receber (valor × cotas).
             */
            total_net?: number | null;
        };
        /**
         * AnnouncedResponse
         * @description Proventos futuros JÁ ANUNCIADOS para os ativos da carteira — agenda real, não sazonalidade.
         */
        AnnouncedResponse: {
            /** Items */
            items?: components["schemas"]["AnnouncedPayment"][];
            /**
             * Total Net
             * @description Soma líquida do que já está anunciado.
             * @default 0
             */
            total_net: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** Warnings */
            warnings?: string[];
        };
        /** Asset */
        Asset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /**
             * Asset Class
             * @description STOCK | FII | ETF | BDR.
             * @default UNKNOWN
             */
            asset_class: string;
            /** Sector */
            sector?: string | null;
            /**
             * Price
             * @description Cotação mais recente (BRL).
             */
            price?: number | null;
            fundamentals?: components["schemas"]["Fundamentals"];
            /**
             * Dividends By Year
             * @description Soma de dividendos por ano (ex: {'2023': 1.2, '2024': 1.4}). Base para preço-teto de Bazin e consistência.
             */
            dividends_by_year?: {
                [key: string]: number;
            };
            /**
             * Lot Size
             * @description Tamanho do lote padrão (FII/ETF normalmente 1).
             * @default 1
             */
            lot_size: number;
            /**
             * Missing
             * @description Quais dados faltaram nesta consulta.
             */
            missing?: string[];
            /**
             * Stale
             * @description True se veio de cache defasado.
             * @default false
             */
            stale: boolean;
            /**
             * As Of
             * @description Carimbo ISO da cotação/fundamentos.
             */
            as_of?: string | null;
            /**
             * Source
             * @description Origem dos dados.
             * @default brapi
             */
            source: string;
        };
        /**
         * AssetDetailResponse
         * @description Detalhe de um ativo: dados crus (fundamentos, proventos) + a pontuação explicada.
         */
        AssetDetailResponse: {
            asset: components["schemas"]["Asset"];
            scored: components["schemas"]["ScoredAsset"];
        };
        /** CalendarMonth */
        CalendarMonth: {
            /** Month */
            month: number;
            /**
             * Income
             * @default 0
             */
            income: number;
            /** By Asset */
            by_asset?: {
                [key: string]: unknown;
            }[];
        };
        /** CalendarResponse */
        CalendarResponse: {
            /** Months */
            months?: components["schemas"]["CalendarMonth"][];
            /**
             * Annual Total
             * @default 0
             */
            annual_total: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /**
             * Basis
             * @default média sazonal dos últimos anos (estimativa, líquida de IR do JCP)
             */
            basis: string;
            /** Warnings */
            warnings?: string[];
        };
        /** EntryIn */
        EntryIn: {
            /**
             * Kind
             * @description balance = atualização de saldo; deposit = aporte; withdrawal = resgate.
             * @enum {string}
             */
            kind: "balance" | "deposit" | "withdrawal";
            /**
             * Amount
             * @description Saldo observado (balance) ou valor (deposit/withdrawal).
             */
            amount: number;
            /**
             * Entry Date
             * @description Data ISO yyyy-mm-dd (padrão: hoje, Brasil).
             */
            entry_date?: string | null;
            /** Note */
            note?: string | null;
        };
        /** FixedIncomeSummary */
        FixedIncomeSummary: {
            /** Accounts */
            accounts?: components["schemas"]["AccountSummary"][];
            /**
             * Total Balance
             * @default 0
             */
            total_balance: number;
            /**
             * Cdi Annual
             * @description CDI anualizado (fração), benchmark.
             */
            cdi_annual?: number | null;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
        };
        /**
         * Fundamentals
         * @description Fundamentos de um ativo. Campos podem ser None quando a brapi não fornece.
         */
        Fundamentals: {
            /**
             * Pvp
             * @description Preço / Valor Patrimonial (priceToBook).
             */
            pvp?: number | null;
            /**
             * Pl
             * @description Preço / Lucro (priceEarnings).
             */
            pl?: number | null;
            /**
             * Dividend Yield
             * @description Dividend yield BRUTO trailing-365d (0..1, ex: 0.092 = 9,2%).
             */
            dividend_yield?: number | null;
            /**
             * Dividend Yield Net
             * @description Dividend yield LÍQUIDO (JCP×0,85; dividendo/FII isentos), trailing-365d.
             */
            dividend_yield_net?: number | null;
            /**
             * Lpa
             * @description Lucro por ação (base do Número de Graham).
             */
            lpa?: number | null;
            /**
             * Vpa
             * @description Valor patrimonial por ação (base do Número de Graham).
             */
            vpa?: number | null;
            /**
             * Market Cap
             * @description Valor de mercado.
             */
            market_cap?: number | null;
            /**
             * Roe
             * @description Return on equity (0..1).
             */
            roe?: number | null;
            /**
             * Net Margin
             * @description Margem líquida (0..1).
             */
            net_margin?: number | null;
            /**
             * Net Debt To Ebitda
             * @description Dívida líquida / EBITDA.
             */
            net_debt_to_ebitda?: number | null;
            /**
             * Current Ratio
             * @description Liquidez corrente (ativo circ./passivo circ.).
             */
            current_ratio?: number | null;
            /**
             * Avg Daily Liquidity
             * @description Volume financeiro médio diário (R$).
             */
            avg_daily_liquidity?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeAsset */
        IncomeAsset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Value */
            value: number;
            /** Dividend Yield */
            dividend_yield: number;
            /** Annual Income */
            annual_income: number;
            /** Cost Basis */
            cost_basis?: number | null;
            /**
             * Yield On Cost
             * @description Renda anual ÷ preço médio pago.
             */
            yield_on_cost?: number | null;
        };
        /**
         * IncomeGoalResponse
         * @description Objetivo de renda: quanto falta e quanto aportar para viver de dividendos.
         *
         *     v4: meta comparada em reais DE HOJE (inflação das preferências), aporte projetado é o
         *     que sobra APÓS o desvio para a reserva, renda da reserva pode contar (opt-in) e há
         *     marcos intermediários ('próximos R$ 100/mês') para a jornada de décadas ter vitórias.
         */
        IncomeGoalResponse: {
            /**
             * Target Monthly Income
             * @default 0
             */
            target_monthly_income: number;
            /**
             * Current Monthly Income
             * @default 0
             */
            current_monthly_income: number;
            /**
             * Gap Monthly
             * @default 0
             */
            gap_monthly: number;
            /**
             * Pct Achieved
             * @default 0
             */
            pct_achieved: number;
            /**
             * Horizon Years
             * @default 20
             */
            horizon_years: number;
            /**
             * Portfolio Yield
             * @default 0
             */
            portfolio_yield: number;
            /** Required Monthly Contribution */
            required_monthly_contribution?: number | null;
            /** Estimated Years To Goal */
            estimated_years_to_goal?: number | null;
            /**
             * Expected Inflation
             * @description Inflação anual usada (preferências).
             * @default 0
             */
            expected_inflation: number;
            /**
             * Reserve Monthly Income
             * @description Renda mensal estimada da reserva/RF (Σ saldo × último rendimento ÷ 12).
             */
            reserve_monthly_income?: number | null;
            /**
             * Include Reserve Income
             * @description Se a renda da RF conta na meta (opt-in).
             * @default false
             */
            include_reserve_income: boolean;
            /**
             * Aporte Rv Estimated
             * @description Aporte que sobra para RV após o desvio para a reserva (usado na projeção).
             */
            aporte_rv_estimated?: number | null;
            /**
             * Next Milestone
             * @description Próximo marco de renda mensal (R$).
             */
            next_milestone?: number | null;
            /**
             * Milestone Gap
             * @description Quanto falta de renda para o marco.
             */
            milestone_gap?: number | null;
            /**
             * Milestone Capital Needed
             * @description Capital adicional ~necessário para o marco (gap×12 ÷ yield).
             */
            milestone_capital_needed?: number | null;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** Warnings */
            warnings?: string[];
        };
        /** IncomeResponse */
        IncomeResponse: {
            /**
             * Annual Income
             * @default 0
             */
            annual_income: number;
            /**
             * Monthly Income
             * @default 0
             */
            monthly_income: number;
            /**
             * Annual Income Gross
             * @description Renda anual bruta (antes do IR do JCP).
             */
            annual_income_gross?: number | null;
            /**
             * Monthly Income Gross
             * @description Renda mensal bruta (antes do IR do JCP).
             */
            monthly_income_gross?: number | null;
            /**
             * Portfolio Yield
             * @default 0
             */
            portfolio_yield: number;
            /**
             * Yield On Cost
             * @description YoC agregado (renda ÷ custo total).
             */
            yield_on_cost?: number | null;
            /**
             * Total Value
             * @default 0
             */
            total_value: number;
            /** By Asset */
            by_asset?: components["schemas"]["IncomeAsset"][];
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** Warnings */
            warnings?: string[];
        };
        /** LoginBody */
        LoginBody: {
            /** Password */
            password: string;
        };
        /**
         * Metric
         * @description Uma sub-métrica do score, com valor cru, normalizado e proveniência.
         *
         *     `available=False` significa que a fonte não tinha o dado; nesse caso o peso é
         *     redistribuído entre as métricas disponíveis (ver services/scoring.py) e
         *     `fallback_used` explica qualquer aproximação aplicada.
         */
        Metric: {
            /**
             * Key
             * @description Identificador da métrica e chave no glossário.
             */
            key: string;
            /**
             * Label
             * @description Rótulo curto para a UI (ex: 'P/VP').
             */
            label: string;
            /**
             * Raw Value
             * @description Valor cru, na unidade original.
             */
            raw_value?: number | null;
            /**
             * Display
             * @description Valor já formatado para exibição.
             */
            display?: string | null;
            /**
             * Normalized
             * @description Valor normalizado em [0,1] (maior = melhor).
             */
            normalized?: number | null;
            /**
             * Weight
             * @description Peso desta métrica no score composto (após renormalizar).
             */
            weight: number;
            /**
             * Contribution
             * @description weight * normalized — quanto somou ao score final.
             */
            contribution?: number | null;
            /**
             * Source
             * @description Origem legível do dado.
             */
            source: string;
            /**
             * Available
             * @description False quando a fonte não tinha o dado.
             * @default true
             */
            available: boolean;
            /**
             * Fallback Used
             * @description Aproximação aplicada quando o dado ideal faltava.
             */
            fallback_used?: string | null;
            /**
             * Peer Group
             * @description Grupo de pares usado na normalização (ex: 'FII/Logística').
             */
            peer_group?: string | null;
        };
        /** OrderIn */
        OrderIn: {
            /** Ticker */
            ticker: string;
            /** Asset Class */
            asset_class?: string | null;
            /**
             * Shares
             * @description Quantidade de cotas/ações compradas.
             */
            shares: number;
            /**
             * Price
             * @description Preço pago por cota (BRL).
             */
            price: number;
            /**
             * Fees
             * @description Custos/corretagem (BRL).
             * @default 0
             */
            fees: number;
            /**
             * Executed At
             * @description Data ISO (padrão: agora).
             */
            executed_at?: string | null;
            /** Note */
            note?: string | null;
            /** Plan Id */
            plan_id?: number | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Asset Class */
            asset_class?: string | null;
            /** Shares */
            shares: number;
            /** Price */
            price: number;
            /**
             * Fees
             * @default 0
             */
            fees: number;
            /** Executed At */
            executed_at?: string | null;
            /** Note */
            note?: string | null;
            /** Plan Id */
            plan_id?: number | null;
        };
        /** OrdersListResponse */
        OrdersListResponse: {
            /** Items */
            items?: components["schemas"]["OrderOut"][];
            /**
             * Total Invested
             * @default 0
             */
            total_invested: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Aporte
             * @description Quanto você tem para investir hoje (BRL).
             */
            aporte: number;
            /**
             * Strategy
             * @description Preset de estratégia: 'equilibrado' | 'barsi' | 'bazin' | 'graham'.
             * @default equilibrado
             */
            strategy: string;
            /**
             * Targets
             * @description Alvos de alocação por classe (0..1). Se omitido, usa o default.
             */
            targets?: {
                [key: string]: number;
            } | null;
            /**
             * Weights
             * @description Pesos das famílias de métricas (valuation/dividend/rebalance/sector). Se informado, sobrepõe o preset.
             */
            weights?: {
                [key: string]: number;
            } | null;
            /**
             * Max Assets
             * @description Máximo de ativos diferentes no plano.
             * @default 5
             */
            max_assets: number;
            /**
             * Max Weight Per Asset
             * @description Teto do peso de um ativo na carteira resultante.
             * @default 0.2
             */
            max_weight_per_asset: number;
            /**
             * Min Ticket
             * @description Valor mínimo para alocar em um único ativo (BRL).
             * @default 100
             */
            min_ticket: number;
            /**
             * Max Weight Per Class
             * @description Teto de peso por classe na carteira resultante.
             */
            max_weight_per_class?: number | null;
            /**
             * Reserve Target
             * @description Fração-alvo em reserva/renda fixa. Se omitido, usa as preferências.
             */
            reserve_target?: number | null;
            /**
             * Reserve Current
             * @description Reserva já existente (BRL). Se omitido, usa o total do rastreador de RF.
             */
            reserve_current?: number | null;
            /**
             * Allow Empty Portfolio
             * @description Permite gerar plano SEM conseguir ler a carteira (fail-open explícito). Por padrão o plano é abortado: alocar dinheiro real sobre carteira vazia produz sugestões materialmente erradas.
             * @default false
             */
            allow_empty_portfolio: boolean;
            /**
             * Focus
             * @description Foco do aporte: 'BALANCE' distribui entre as classes conforme as metas; uma classe (STOCK/FII/ETF/BDR) concentra todo o aporte de RV nela. Se omitido, usa a preferência salva.
             */
            focus?: string | null;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Aporte */
            aporte: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** As Of */
            as_of: string;
            /**
             * Weights
             * @description Pesos usados no score (visíveis para a UI).
             */
            weights?: {
                [key: string]: number;
            };
            /** Targets By Class */
            targets_by_class?: {
                [key: string]: number;
            };
            /** Current By Class */
            current_by_class?: {
                [key: string]: number;
            };
            /** Ranking */
            ranking?: components["schemas"]["ScoredAsset"][];
            /**
             * Unallocated
             * @description Sobra do aporte não alocada (BRL).
             * @default 0
             */
            unallocated: number;
            /** @description Sugestão de reserva/renda fixa (quando há reserve_target). */
            reserve?: components["schemas"]["ReserveSuggestion"] | null;
            /** Warnings */
            warnings?: string[];
            /**
             * Focus
             * @description Foco usado no plano: 'BALANCE' ou uma classe (STOCK/FII/ETF/BDR).
             */
            focus?: string | null;
            /**
             * Plan Id
             * @description Id do plano persistido (plan_history).
             */
            plan_id?: number | null;
            /**
             * Created At
             * @description Quando o plano foi gerado (planos salvos).
             */
            created_at?: string | null;
            /**
             * Disclaimer
             * @default Conteúdo educativo. Não é recomendação de investimento. Os dados podem estar defasados; confira antes de operar.
             */
            disclaimer: string;
        };
        /**
         * PlanSummary
         * @description Resumo de um plano salvo (lista 'Planos anteriores').
         */
        PlanSummary: {
            /** Id */
            id: number;
            /** Created At */
            created_at?: string | null;
            /** Aporte */
            aporte?: number | null;
            /** Strategy */
            strategy?: string | null;
            /** Suggested Count */
            suggested_count?: number | null;
        };
        /** Portfolio */
        Portfolio: {
            /**
             * Total Value
             * @description Valor total da carteira (BRL).
             */
            total_value: number;
            /**
             * Currency
             * @description Moeda de referência.
             * @default BRL
             */
            currency: string;
            /** Positions */
            positions?: components["schemas"]["Position"][];
            allocations?: components["schemas"]["Allocations"];
            /**
             * As Of
             * @description Carimbo ISO da leitura.
             */
            as_of: string;
            /**
             * Source
             * @description Origem dos dados.
             * @default ghostfolio
             */
            source: string;
            /** Warnings */
            warnings?: string[];
        };
        /** Position */
        Position: {
            /**
             * Ticker
             * @description Símbolo do ativo (ex: 'BBAS3').
             */
            ticker: string;
            /**
             * Name
             * @description Nome do ativo, se disponível.
             */
            name?: string | null;
            /**
             * Asset Class
             * @description STOCK | FII | ETF | BDR | UNKNOWN.
             * @default UNKNOWN
             */
            asset_class: string;
            /**
             * Sector
             * @description Setor, se conhecido.
             */
            sector?: string | null;
            /**
             * Value
             * @description Valor de mercado da posição (BRL).
             */
            value: number;
            /**
             * Weight
             * @description Peso na carteira (0..1).
             */
            weight: number;
            /**
             * Quantity
             * @description Quantidade de cotas/ações.
             */
            quantity?: number | null;
            /**
             * Cost Basis
             * @description Custo total da posição (BRL), se conhecido.
             */
            cost_basis?: number | null;
            /**
             * Average Price
             * @description Preço médio de compra (BRL).
             */
            average_price?: number | null;
            /**
             * Net Performance Pct
             * @description Rentabilidade líquida da posição (fração) — do Ghostfolio, se disponível.
             */
            net_performance_pct?: number | null;
            /**
             * Tags
             * @description Tags do Ghostfolio nesta posição.
             */
            tags?: string[];
            /**
             * Source
             * @description Origem do dado.
             * @default ghostfolio:holdings
             */
            source: string;
        };
        /**
         * PreferencesBody
         * @description Campos opcionais — só os enviados são atualizados (patch).
         */
        PreferencesBody: {
            /** Strategy */
            strategy?: string | null;
            /** Aporte Default */
            aporte_default?: number | null;
            /** Targets */
            targets?: {
                [key: string]: unknown;
            } | null;
            /** Weights */
            weights?: {
                [key: string]: unknown;
            } | null;
            /** Max Assets */
            max_assets?: number | null;
            /** Max Weight Per Asset */
            max_weight_per_asset?: number | null;
            /** Min Ticket */
            min_ticket?: number | null;
            /** Lot Mode */
            lot_mode?: string | null;
            /** Reserve Target */
            reserve_target?: number | null;
            /** Bazin Target Mode */
            bazin_target_mode?: string | null;
            /** Bazin Target Yield */
            bazin_target_yield?: number | null;
            /** Target Monthly Income */
            target_monthly_income?: number | null;
            /** Target Horizon Years */
            target_horizon_years?: number | null;
            /** Annual Growth */
            annual_growth?: number | null;
            /** Expected Inflation */
            expected_inflation?: number | null;
            /** Include Reserve Income */
            include_reserve_income?: boolean | null;
            /** Focus */
            focus?: string | null;
            /** Class Targets */
            class_targets?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
        };
        /** ProjectionPoint */
        ProjectionPoint: {
            /** Year */
            year: number;
            /** Value */
            value: number;
            /** Invested */
            invested: number;
            /** Annual Income */
            annual_income: number;
            /** Monthly Income */
            monthly_income: number;
            /**
             * Monthly Income Real
             * @description Renda mensal em reais DE HOJE (deflacionada pela inflação esperada).
             */
            monthly_income_real?: number | null;
        };
        /** ProjectionRequest */
        ProjectionRequest: {
            /**
             * Current Value
             * @default 0
             */
            current_value: number;
            /**
             * Monthly Contribution
             * @default 0
             */
            monthly_contribution: number;
            /**
             * Annual Yield
             * @description DY anual em fração (0..1).
             */
            annual_yield: number;
            /**
             * Annual Growth
             * @description Crescimento anual do patrimônio que acompanha os proventos (-0.5..1).
             * @default 0
             */
            annual_growth: number;
            /**
             * Annual Inflation
             * @description Inflação anual esperada — deflaciona para reais de hoje.
             * @default 0
             */
            annual_inflation: number;
            /**
             * Years
             * @default 20
             */
            years: number;
            /**
             * Reinvest
             * @default true
             */
            reinvest: boolean;
            /**
             * Target Monthly Income
             * @description Se informado, calcula o aporte mensal necessário para essa renda.
             */
            target_monthly_income?: number | null;
        };
        /** ProjectionResponse */
        ProjectionResponse: {
            /** Series */
            series?: components["schemas"]["ProjectionPoint"][];
            /**
             * Final Value
             * @default 0
             */
            final_value: number;
            /**
             * Final Monthly Income
             * @default 0
             */
            final_monthly_income: number;
            /**
             * Final Monthly Income Real
             * @description Renda mensal final em reais de hoje (igual à nominal com inflação 0).
             */
            final_monthly_income_real?: number | null;
            /**
             * Total Invested
             * @default 0
             */
            total_invested: number;
            /**
             * Total Dividends
             * @default 0
             */
            total_dividends: number;
            /** Required Monthly Contribution */
            required_monthly_contribution?: number | null;
        };
        /**
         * RadarItem
         * @description Linha do radar: os dados de DECISÃO de cada ativo observado.
         */
        RadarItem: {
            /** Ticker */
            ticker: string;
            /**
             * Asset Class
             * @default STOCK
             */
            asset_class: string;
            /** Price */
            price?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Dividend Yield Net */
            dividend_yield_net?: number | null;
            /** Ceiling Price */
            ceiling_price?: number | null;
            /**
             * Margin
             * @description (teto − preço) ÷ teto; positivo = desconto.
             */
            margin?: number | null;
            /** Below Ceiling */
            below_ceiling?: boolean | null;
            /**
             * In Portfolio
             * @default false
             */
            in_portfolio: boolean;
        };
        /** RadarResponse */
        RadarResponse: {
            /** Items */
            items?: components["schemas"]["RadarItem"][];
            /**
             * Bazin Target Yield
             * @default 0.06
             */
            bazin_target_yield: number;
            /**
             * Below Count
             * @default 0
             */
            below_count: number;
            /** Warnings */
            warnings?: string[];
        };
        /** RealizedAsset */
        RealizedAsset: {
            /** Ticker */
            ticker: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * RealizedIncomeResponse
         * @description Renda REALIZADA: dividendos que efetivamente caíram na conta (fonte: Ghostfolio).
         *
         *     É o contraponto da renda estimada (valor × DY): a série real da bola de neve.
         */
        RealizedIncomeResponse: {
            /**
             * Months
             * @description Últimos 24 meses.
             */
            months?: components["schemas"]["RealizedMonth"][];
            /**
             * Total 12M
             * @default 0
             */
            total_12m: number;
            /**
             * Monthly Avg 12M
             * @default 0
             */
            monthly_avg_12m: number;
            /** By Asset 12M */
            by_asset_12m?: components["schemas"]["RealizedAsset"][];
            /**
             * Last Payments
             * @description Pagamentos mais recentes.
             */
            last_payments?: components["schemas"]["RealizedPayment"][];
            /**
             * Total 30D
             * @description Recebido nos últimos 30 dias (base do reinvestimento).
             * @default 0
             */
            total_30d: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** Warnings */
            warnings?: string[];
        };
        /** RealizedMonth */
        RealizedMonth: {
            /** Month */
            month: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** RealizedPayment */
        RealizedPayment: {
            /** Date */
            date: string;
            /** Ticker */
            ticker: string;
            /** Value */
            value: number;
        };
        /**
         * ReserveSuggestion
         * @description Quanto do aporte direcionar à reserva/renda fixa antes da renda variável (Barsi/Bazin).
         */
        ReserveSuggestion: {
            /**
             * Target Amount
             * @description Alvo de reserva em BRL (reserve_target × patrimônio).
             */
            target_amount: number;
            /**
             * Current Amount
             * @description Reserva atual (BRL) — do rastreador de renda fixa.
             */
            current_amount: number;
            /**
             * Gap
             * @description Quanto falta para a reserva-alvo (BRL).
             */
            gap: number;
            /**
             * Pct Filled
             * @description Fração da reserva-alvo já preenchida (0..1).
             */
            pct_filled: number;
            /**
             * Directed Now
             * @description Quanto deste aporte vai para a reserva (BRL).
             */
            directed_now: number;
            /**
             * Benchmark Cdi Annual
             * @description CDI anualizado (fração), referência.
             */
            benchmark_cdi_annual?: number | null;
            /**
             * Note
             * @default Complete a reserva/CDI antes da renda variável.
             */
            note: string;
        };
        /** ScoredAsset */
        ScoredAsset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /**
             * Asset Class
             * @default UNKNOWN
             */
            asset_class: string;
            /** Sector */
            sector?: string | null;
            /**
             * Rank
             * @default 0
             */
            rank: number;
            /**
             * Composite Score
             * @description Score final (0..1), média ponderada das métricas.
             */
            composite_score: number;
            /** Metrics */
            metrics?: components["schemas"]["Metric"][];
            /**
             * Data Completeness
             * @description Métricas disponíveis vs totais, ex: '3/4'.
             * @default 0/0
             */
            data_completeness: string;
            suggested?: components["schemas"]["SuggestedBuy"] | null;
            /**
             * Reasons
             * @description Frases curtas explicando por que o ativo subiu no ranking.
             */
            reasons?: string[];
            /**
             * Composite Base
             * @description Score antes do fator de qualidade/risco (auditoria).
             * @default 0
             */
            composite_base: number;
            /**
             * Quality Factor
             * @description Fator de qualidade/risco em [0,1] que multiplica o score (1 = sem penalidade).
             * @default 1
             */
            quality_factor: number;
            /**
             * Risk Level
             * @description Selo de risco: verde | amarelo | vermelho.
             * @default verde
             */
            risk_level: string;
            /**
             * Red Flags
             * @description Pontos de atenção (por que NÃO comprar).
             */
            red_flags?: string[];
            /**
             * Bazin Ceiling Price
             * @description Preço-teto de Bazin em BRL (dividendo médio ÷ DY-alvo). None se indisponível.
             */
            bazin_ceiling_price?: number | null;
            /**
             * Bazin Below Ceiling
             * @description True se o preço atual está abaixo do teto (zona de compra).
             */
            bazin_below_ceiling?: boolean | null;
            /**
             * Bazin Margin
             * @description Margem sobre o teto em [-1,1] (positivo = comprando com desconto).
             */
            bazin_margin?: number | null;
        };
        /** SnapshotPoint */
        SnapshotPoint: {
            /** Month */
            month: string;
            /** Total Value */
            total_value?: number | null;
            /** Annual Income */
            annual_income?: number | null;
            /** Monthly Income */
            monthly_income?: number | null;
            /** Portfolio Yield */
            portfolio_yield?: number | null;
            /** Yield On Cost */
            yield_on_cost?: number | null;
        };
        /**
         * SnapshotsResponse
         * @description Série mensal REAL da carteira (patrimônio, renda estimada, YoC) — a prova visual
         *     da bola de neve. Alimentada por um snapshot automático por mês.
         */
        SnapshotsResponse: {
            /** Months */
            months?: components["schemas"]["SnapshotPoint"][];
            /**
             * Currency
             * @default BRL
             */
            currency: string;
        };
        /**
         * SuggestedBuy
         * @description Quanto comprar de um ativo — com a aritmética completa, auditável.
         */
        SuggestedBuy: {
            /**
             * Target Amount
             * @description Valor-alvo a aportar neste ativo (BRL).
             */
            target_amount: number;
            /**
             * Price
             * @description Cotação usada no cálculo (BRL).
             */
            price?: number | null;
            /**
             * Shares
             * @description Número inteiro de cotas/ações sugerido.
             * @default 0
             */
            shares: number;
            /**
             * Invested Exact
             * @description shares * price — gasto real estimado.
             * @default 0
             */
            invested_exact: number;
            /**
             * Lot Size
             * @description Tamanho do lote considerado.
             * @default 1
             */
            lot_size: number;
            /**
             * Lot Note
             * @description Observação sobre lote/arredondamento.
             */
            lot_note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistAdd */
        WatchlistAdd: {
            /** Ticker */
            ticker: string;
            /** Note */
            note?: string | null;
        };
        /** WatchlistPatch */
        WatchlistPatch: {
            /** Favorite */
            favorite: boolean;
        };
        /** YocPoint */
        YocPoint: {
            /** Month */
            month: string;
            /** Yoc */
            yoc?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    glossary_api_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_brapi_api_debug_brapi_get: {
        parameters: {
            query?: {
                ticker?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
    universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    asset_api_asset__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_latest_api_plan_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
        };
    };
    plan_history_api_plan_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_preferences_api_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    add_to_watchlist_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_api_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_watchlist_api_watchlist__ticker__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_radar_api_watchlist_radar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarResponse"];
                };
            };
        };
    };
    income_api_income_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeResponse"];
                };
            };
        };
    };
    income_snapshots_api_income_snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsResponse"];
                };
            };
        };
    };
    yoc_history_api_income_yoc__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YocPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projection_api_income_projection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    income_goal_api_income_goal_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeGoalResponse"];
                };
            };
        };
    };
    income_realized_api_income_realized_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealizedIncomeResponse"];
                };
            };
        };
    };
    income_announced_api_income_announced_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncedResponse"];
                };
            };
        };
    };
    income_calendar_api_income_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
        };
    };
    fixed_income_summary_api_fixed_income_summary_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixedIncomeSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_fixed_income_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_account_api_fixed_income_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_fixed_income_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_fixed_income_accounts__account_id__entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_entry_api_fixed_income_accounts__account_id__entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_api_fixed_income_accounts__account_id__entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_order_api_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
