/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary */
        get: operations["glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/brapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Brapi
         * @description Diagnóstico da conexão com a brapi (status HTTP, token presente, resposta crua).
         *
         *     NÃO expõe o token — só o tamanho. Disponível apenas com DEBUG=true (404 caso contrário),
         *     para não vazar configuração em produção.
         */
        get: operations["debug_brapi_api_debug_brapi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe */
        get: operations["universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asset
         * @description Detalhe completo do ativo: classe+setor canônicos, fundamentos (incl. LPA/VPA),
         *     histórico de proventos e a leitura factual (preço-teto, consistência, red flags).
         */
        get: operations["asset_api_asset__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan Latest
         * @description Último plano gerado (persistido) — para a PlanPage restaurar ao montar.
         */
        get: operations["plan_latest_api_plan_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan History
         * @description Planos anteriores (resumo): quando, quanto e quantas compras foram sugeridas.
         */
        get: operations["plan_history_api_plan_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_preferences_get"];
        /** Put Preferences */
        put: operations["put_preferences_api_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_api_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_api_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watchlist Radar
         * @description Radar de zona de compra: preço, DY e situação vs preço-teto de Bazin de TODOS os
         *     ativos observados — a watchlist deixa de ser lista inerte e responde 'é hora de
         *     comprar?' sem abrir ativo por ativo. Ordenado pela margem sobre o teto.
         */
        get: operations["watchlist_radar_api_watchlist_radar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income
         * @description Renda passiva atual estimada da carteira (Σ valor × DY) + Yield on Cost por ativo.
         */
        get: operations["income_api_income_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/yoc/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yoc History
         * @description Histórico mensal do Yield on Cost de um ativo (dos snapshots).
         */
        get: operations["yoc_history_api_income_yoc__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixed Income Summary */
        get: operations["fixed_income_summary_api_fixed_income_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Account */
        post: operations["create_account_api_fixed_income_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive Account */
        delete: operations["archive_account_api_fixed_income_accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_api_fixed_income_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/fixed-income/accounts/{account_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_fixed_income_accounts__account_id__entries_get"];
        put?: never;
        /** Add Entry */
        post: operations["add_entry_api_fixed_income_accounts__account_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/accounts/{account_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_api_fixed_income_accounts__account_id__entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Order */
        delete: operations["delete_order_api_orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountIn */
        AccountIn: {
            /**
             * Name
             * @description Ex.: 'CDB Banco X', 'Tesouro Selic 2029', 'Conta'.
             */
            name: string;
            /** Institution */
            institution?: string | null;
            /**
             * Kind
             * @description 'cdb'|'tesouro'|'poupanca'|'conta'|'outro'.
             */
            kind?: string | null;
            /**
             * Benchmark
             * @description 'cdi'|'selic'|'prefixado'|'ipca' (informativo).
             */
            benchmark?: string | null;
        };
        /**
         * AccountPatch
         * @description PATCH parcial da conta: só os campos enviados mudam. `archived=False` desarquiva —
         *     arquivar deixou de ser sem-volta na UI.
         */
        AccountPatch: {
            /** Name */
            name?: string | null;
            /** Institution */
            institution?: string | null;
            /** Kind */
            kind?: string | null;
            /** Benchmark */
            benchmark?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** AccountSummary */
        AccountSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Institution */
            institution?: string | null;
            /** Kind */
            kind?: string | null;
            /** Benchmark */
            benchmark?: string | null;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Current Balance
             * @default 0
             */
            current_balance: number;
            /**
             * Last Yield Annual
             * @description Rendimento anualizado (fração).
             */
            last_yield_annual?: number | null;
            /**
             * Last Yield Gain
             * @description Ganho do período (BRL).
             */
            last_yield_gain?: number | null;
            /** Last Yield From */
            last_yield_from?: string | null;
            /** Last Yield To */
            last_yield_to?: string | null;
            /** Last Yield Business Days */
            last_yield_business_days?: number | null;
            /**
             * Pct Of Cdi
             * @description Rendimento como fração do CDI (1.0 = 100%).
             */
            pct_of_cdi?: number | null;
        };
        /** Allocations */
        Allocations: {
            /**
             * By Class
             * @description Peso por classe (0..1).
             */
            by_class?: {
                [key: string]: number;
            };
            /**
             * By Sector
             * @description Peso por setor (0..1).
             */
            by_sector?: {
                [key: string]: number;
            };
        };
        /** Asset */
        Asset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /**
             * Asset Class
             * @description STOCK | FII | ETF | BDR.
             * @default UNKNOWN
             */
            asset_class: string;
            /** Sector */
            sector?: string | null;
            /**
             * Price
             * @description Cotação mais recente (BRL).
             */
            price?: number | null;
            fundamentals?: components["schemas"]["Fundamentals"];
            /**
             * Dividends By Year
             * @description Soma de dividendos por ano (ex: {'2023': 1.2, '2024': 1.4}). Base para preço-teto de Bazin e consistência.
             */
            dividends_by_year?: {
                [key: string]: number;
            };
            /**
             * Lot Size
             * @description Tamanho do lote padrão (FII/ETF normalmente 1).
             * @default 1
             */
            lot_size: number;
            /**
             * Missing
             * @description Quais dados faltaram nesta consulta.
             */
            missing?: string[];
            /**
             * Stale
             * @description True se veio de cache defasado.
             * @default false
             */
            stale: boolean;
            /**
             * As Of
             * @description Carimbo ISO da cotação/fundamentos.
             */
            as_of?: string | null;
            /**
             * Source
             * @description Origem dos dados.
             * @default brapi
             */
            source: string;
        };
        /**
         * AssetAnalysis
         * @description Leitura FACTUAL de um ativo — sem nota, sem ranking, sem estratégia.
         *
         *     Números calculados a partir das fontes (preço-teto de Bazin, consistência e
         *     crescimento dos proventos, payout) e os alertas que decorrem deles.
         */
        AssetAnalysis: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /**
             * Asset Class
             * @default UNKNOWN
             */
            asset_class: string;
            /** Sector */
            sector?: string | null;
            /** Price */
            price?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /**
             * Dividend Yield Net
             * @description DY líquido (JCP ×0,85).
             */
            dividend_yield_net?: number | null;
            /** Bazin Ceiling Price */
            bazin_ceiling_price?: number | null;
            /** Bazin Below Ceiling */
            bazin_below_ceiling?: boolean | null;
            /** Bazin Margin */
            bazin_margin?: number | null;
            /**
             * Bazin Target Yield
             * @description DY-alvo usado no preço-teto.
             * @default 0.06
             */
            bazin_target_yield: number;
            /**
             * Dividend Consistency
             * @description Anos pagos ÷ anos analisados, penalizando cortes fortes (0..1).
             */
            dividend_consistency?: number | null;
            /**
             * Dividend Cagr
             * @description Crescimento anual dos proventos (fração).
             */
            dividend_cagr?: number | null;
            /**
             * Payout Ratio
             * @description Provento médio ÷ LPA (fração).
             */
            payout_ratio?: number | null;
            /**
             * Risk Level
             * @default verde
             */
            risk_level: string;
            /** Red Flags */
            red_flags?: string[];
            /**
             * Highlights
             * @description Pontos factuais favoráveis.
             */
            highlights?: string[];
        };
        /**
         * AssetDetailResponse
         * @description Detalhe de um ativo: dados crus (fundamentos, proventos) + a leitura factual.
         */
        AssetDetailResponse: {
            asset: components["schemas"]["Asset"];
            analysis: components["schemas"]["AssetAnalysis"];
        };
        /** EntryIn */
        EntryIn: {
            /**
             * Kind
             * @description balance = atualização de saldo; deposit = aporte; withdrawal = resgate.
             * @enum {string}
             */
            kind: "balance" | "deposit" | "withdrawal";
            /**
             * Amount
             * @description Saldo observado (balance) ou valor (deposit/withdrawal).
             */
            amount: number;
            /**
             * Entry Date
             * @description Data ISO yyyy-mm-dd (padrão: hoje, Brasil).
             */
            entry_date?: string | null;
            /** Note */
            note?: string | null;
        };
        /** FixedIncomeSummary */
        FixedIncomeSummary: {
            /** Accounts */
            accounts?: components["schemas"]["AccountSummary"][];
            /**
             * Total Balance
             * @default 0
             */
            total_balance: number;
            /**
             * Cdi Annual
             * @description CDI anualizado (fração), benchmark.
             */
            cdi_annual?: number | null;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
        };
        /**
         * Fundamentals
         * @description Fundamentos de um ativo. Campos podem ser None quando a brapi não fornece.
         */
        Fundamentals: {
            /**
             * Pvp
             * @description Preço / Valor Patrimonial (priceToBook).
             */
            pvp?: number | null;
            /**
             * Pl
             * @description Preço / Lucro (priceEarnings).
             */
            pl?: number | null;
            /**
             * Dividend Yield
             * @description Dividend yield BRUTO trailing-365d (0..1, ex: 0.092 = 9,2%).
             */
            dividend_yield?: number | null;
            /**
             * Dividend Yield Net
             * @description Dividend yield LÍQUIDO (JCP×0,85; dividendo/FII isentos), trailing-365d.
             */
            dividend_yield_net?: number | null;
            /**
             * Lpa
             * @description Lucro por ação (base do Número de Graham).
             */
            lpa?: number | null;
            /**
             * Vpa
             * @description Valor patrimonial por ação (base do Número de Graham).
             */
            vpa?: number | null;
            /**
             * Market Cap
             * @description Valor de mercado.
             */
            market_cap?: number | null;
            /**
             * Roe
             * @description Return on equity (0..1).
             */
            roe?: number | null;
            /**
             * Net Margin
             * @description Margem líquida (0..1).
             */
            net_margin?: number | null;
            /**
             * Net Debt To Ebitda
             * @description Dívida líquida / EBITDA.
             */
            net_debt_to_ebitda?: number | null;
            /**
             * Current Ratio
             * @description Liquidez corrente (ativo circ./passivo circ.).
             */
            current_ratio?: number | null;
            /**
             * Avg Daily Liquidity
             * @description Volume financeiro médio diário (R$).
             */
            avg_daily_liquidity?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeAsset */
        IncomeAsset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Value */
            value: number;
            /** Dividend Yield */
            dividend_yield: number;
            /** Annual Income */
            annual_income: number;
            /** Cost Basis */
            cost_basis?: number | null;
            /**
             * Yield On Cost
             * @description Renda anual ÷ preço médio pago.
             */
            yield_on_cost?: number | null;
        };
        /** IncomeResponse */
        IncomeResponse: {
            /**
             * Annual Income
             * @default 0
             */
            annual_income: number;
            /**
             * Monthly Income
             * @default 0
             */
            monthly_income: number;
            /**
             * Annual Income Gross
             * @description Renda anual bruta (antes do IR do JCP).
             */
            annual_income_gross?: number | null;
            /**
             * Monthly Income Gross
             * @description Renda mensal bruta (antes do IR do JCP).
             */
            monthly_income_gross?: number | null;
            /**
             * Portfolio Yield
             * @default 0
             */
            portfolio_yield: number;
            /**
             * Yield On Cost
             * @description YoC agregado (renda ÷ custo total).
             */
            yield_on_cost?: number | null;
            /**
             * Total Value
             * @default 0
             */
            total_value: number;
            /** By Asset */
            by_asset?: components["schemas"]["IncomeAsset"][];
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** Warnings */
            warnings?: string[];
        };
        /** LoginBody */
        LoginBody: {
            /** Password */
            password: string;
        };
        /** OrderIn */
        OrderIn: {
            /** Ticker */
            ticker: string;
            /** Asset Class */
            asset_class?: string | null;
            /**
             * Shares
             * @description Quantidade de cotas/ações compradas.
             */
            shares: number;
            /**
             * Price
             * @description Preço pago por cota (BRL).
             */
            price: number;
            /**
             * Fees
             * @description Custos/corretagem (BRL).
             * @default 0
             */
            fees: number;
            /**
             * Executed At
             * @description Data ISO (padrão: agora).
             */
            executed_at?: string | null;
            /** Note */
            note?: string | null;
            /** Plan Id */
            plan_id?: number | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Asset Class */
            asset_class?: string | null;
            /** Shares */
            shares: number;
            /** Price */
            price: number;
            /**
             * Fees
             * @default 0
             */
            fees: number;
            /** Executed At */
            executed_at?: string | null;
            /** Note */
            note?: string | null;
            /** Plan Id */
            plan_id?: number | null;
        };
        /** OrdersListResponse */
        OrdersListResponse: {
            /** Items */
            items?: components["schemas"]["OrderOut"][];
            /**
             * Total Invested
             * @default 0
             */
            total_invested: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
        };
        /**
         * PlanAsset
         * @description Um ativo da carteira alvo dentro do plano.
         *
         *     Só `ticker` é obrigatório: planos antigos, persistidos com outro formato, precisam
         *     continuar sendo lidos por GET /plan/latest (campo que falta vira default).
         */
        PlanAsset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /**
             * Asset Class
             * @default UNKNOWN
             */
            asset_class: string;
            /** Sector */
            sector?: string | null;
            /** Price */
            price?: number | null;
            /**
             * Dividend Yield
             * @description DY anual em fração (0..1).
             */
            dividend_yield?: number | null;
            /**
             * Basket Target Pct
             * @description Peso-alvo do ativo na cesta da classe, definido pelo usuário.
             */
            basket_target_pct?: number | null;
            /**
             * Basket Current Pct
             * @description Peso atual do ativo na cesta (valor dele ÷ valor da cesta hoje).
             */
            basket_current_pct?: number | null;
            /**
             * Basket After Pct
             * @description Peso do ativo na cesta DEPOIS das compras sugeridas.
             */
            basket_after_pct?: number | null;
            /**
             * Basket Gap Brl
             * @description Quanto falta em R$ para o peso-alvo, medido sobre a cesta já com o aporte (positivo = abaixo do alvo; é isto que determina a compra).
             */
            basket_gap_brl?: number | null;
            /**
             * Bazin Ceiling Price
             * @description Preço-teto de Bazin em BRL (dividendo médio ÷ DY-alvo). None se indisponível.
             */
            bazin_ceiling_price?: number | null;
            /**
             * Bazin Below Ceiling
             * @description True se o preço atual está abaixo do teto (zona de compra).
             */
            bazin_below_ceiling?: boolean | null;
            /**
             * Bazin Margin
             * @description Margem sobre o teto em [-1,1] (positivo = comprando com desconto).
             */
            bazin_margin?: number | null;
            /**
             * Risk Level
             * @description Selo de risco factual: verde | amarelo | vermelho.
             * @default verde
             */
            risk_level: string;
            /**
             * Red Flags
             * @description Pontos de atenção (por que olhar duas vezes).
             */
            red_flags?: string[];
            /**
             * Reasons
             * @description Frases curtas explicando a sugestão (ou a ausência dela).
             */
            reasons?: string[];
            suggested?: components["schemas"]["SuggestedBuy"] | null;
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Aporte
             * @description Quanto você tem para investir hoje (BRL).
             */
            aporte: number;
            /**
             * Classes
             * @description Classes que devem receber este aporte (STOCK/FII/ETF/BDR). Omitido = todas. Lista vazia é erro (não há o que planejar).
             */
            classes?: string[] | null;
            /**
             * Targets
             * @description Alvos de alocação por classe (0..1). Se omitido, usa o default.
             */
            targets?: {
                [key: string]: number;
            } | null;
            /**
             * Min Ticket
             * @description Valor mínimo para ABRIR posição em um ativo (BRL).
             * @default 100
             */
            min_ticket: number;
            /**
             * Reserve Target
             * @description Fração-alvo em reserva/renda fixa. Se omitido, usa as preferências.
             */
            reserve_target?: number | null;
            /**
             * Reserve Current
             * @description Reserva já existente (BRL). Se omitido, usa o total do rastreador de RF.
             */
            reserve_current?: number | null;
            /**
             * Allow Empty Portfolio
             * @description Permite gerar plano SEM conseguir ler a carteira (fail-open explícito). Por padrão o plano é abortado: alocar dinheiro real sobre carteira vazia produz sugestões materialmente erradas.
             * @default false
             */
            allow_empty_portfolio: boolean;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Aporte */
            aporte: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** As Of */
            as_of: string;
            /** Targets By Class */
            targets_by_class?: {
                [key: string]: number;
            };
            /** Current By Class */
            current_by_class?: {
                [key: string]: number;
            };
            /** Ranking */
            ranking?: components["schemas"]["PlanAsset"][];
            /**
             * Unallocated
             * @description Sobra do aporte não alocada (BRL).
             * @default 0
             */
            unallocated: number;
            /** @description Sugestão de reserva/renda fixa (quando há reserve_target). */
            reserve?: components["schemas"]["ReserveSuggestion"] | null;
            /**
             * Classes Applied
             * @description Classes marcadas que tinham composição e entraram no plano.
             */
            classes_applied?: string[];
            /**
             * Classes Skipped
             * @description Classes marcadas SEM composição definida — puladas.
             */
            classes_skipped?: string[];
            /** Warnings */
            warnings?: string[];
            /**
             * Plan Id
             * @description Id do plano persistido (plan_history).
             */
            plan_id?: number | null;
            /**
             * Created At
             * @description Quando o plano foi gerado (planos salvos).
             */
            created_at?: string | null;
            /**
             * Disclaimer
             * @default Conteúdo educativo. Não é recomendação de investimento. Os dados podem estar defasados; confira antes de operar.
             */
            disclaimer: string;
        };
        /**
         * PlanSummary
         * @description Resumo de um plano salvo (lista 'Planos anteriores').
         */
        PlanSummary: {
            /** Id */
            id: number;
            /** Created At */
            created_at?: string | null;
            /** Aporte */
            aporte?: number | null;
            /** Suggested Count */
            suggested_count?: number | null;
        };
        /** Portfolio */
        Portfolio: {
            /**
             * Total Value
             * @description Valor total da carteira (BRL).
             */
            total_value: number;
            /**
             * Currency
             * @description Moeda de referência.
             * @default BRL
             */
            currency: string;
            /** Positions */
            positions?: components["schemas"]["Position"][];
            allocations?: components["schemas"]["Allocations"];
            /**
             * As Of
             * @description Carimbo ISO da leitura.
             */
            as_of: string;
            /**
             * Source
             * @description Origem dos dados.
             * @default ghostfolio
             */
            source: string;
            /** Warnings */
            warnings?: string[];
        };
        /** Position */
        Position: {
            /**
             * Ticker
             * @description Símbolo do ativo (ex: 'BBAS3').
             */
            ticker: string;
            /**
             * Name
             * @description Nome do ativo, se disponível.
             */
            name?: string | null;
            /**
             * Asset Class
             * @description STOCK | FII | ETF | BDR | UNKNOWN.
             * @default UNKNOWN
             */
            asset_class: string;
            /**
             * Sector
             * @description Setor, se conhecido.
             */
            sector?: string | null;
            /**
             * Value
             * @description Valor de mercado da posição (BRL).
             */
            value: number;
            /**
             * Weight
             * @description Peso na carteira (0..1).
             */
            weight: number;
            /**
             * Quantity
             * @description Quantidade de cotas/ações.
             */
            quantity?: number | null;
            /**
             * Cost Basis
             * @description Custo total da posição (BRL), se conhecido.
             */
            cost_basis?: number | null;
            /**
             * Average Price
             * @description Preço médio de compra (BRL).
             */
            average_price?: number | null;
            /**
             * Net Performance Pct
             * @description Rentabilidade líquida da posição (fração) — do Ghostfolio, se disponível.
             */
            net_performance_pct?: number | null;
            /**
             * Source
             * @description Origem do dado.
             * @default ghostfolio:holdings
             */
            source: string;
        };
        /**
         * PreferencesBody
         * @description Campos opcionais — só os enviados são atualizados (patch).
         */
        PreferencesBody: {
            /** Aporte Default */
            aporte_default?: number | null;
            /** Targets */
            targets?: {
                [key: string]: unknown;
            } | null;
            /** Min Ticket */
            min_ticket?: number | null;
            /** Lot Mode */
            lot_mode?: string | null;
            /** Reserve Target */
            reserve_target?: number | null;
            /** Bazin Target Mode */
            bazin_target_mode?: string | null;
            /** Bazin Target Yield */
            bazin_target_yield?: number | null;
            /** Class Targets */
            class_targets?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
        };
        /**
         * RadarItem
         * @description Linha do radar: os dados de DECISÃO de cada ativo observado.
         */
        RadarItem: {
            /** Ticker */
            ticker: string;
            /**
             * Asset Class
             * @default STOCK
             */
            asset_class: string;
            /** Price */
            price?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Dividend Yield Net */
            dividend_yield_net?: number | null;
            /** Ceiling Price */
            ceiling_price?: number | null;
            /**
             * Margin
             * @description (teto − preço) ÷ teto; positivo = desconto.
             */
            margin?: number | null;
            /** Below Ceiling */
            below_ceiling?: boolean | null;
            /**
             * In Portfolio
             * @default false
             */
            in_portfolio: boolean;
        };
        /** RadarResponse */
        RadarResponse: {
            /** Items */
            items?: components["schemas"]["RadarItem"][];
            /**
             * Bazin Target Yield
             * @default 0.06
             */
            bazin_target_yield: number;
            /**
             * Below Count
             * @default 0
             */
            below_count: number;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ReserveSuggestion
         * @description Quanto do aporte direcionar à reserva/renda fixa antes da renda variável (Barsi/Bazin).
         */
        ReserveSuggestion: {
            /**
             * Target Amount
             * @description Alvo de reserva em BRL (reserve_target × patrimônio).
             */
            target_amount: number;
            /**
             * Current Amount
             * @description Reserva atual (BRL) — do rastreador de renda fixa.
             */
            current_amount: number;
            /**
             * Gap
             * @description Quanto falta para a reserva-alvo (BRL).
             */
            gap: number;
            /**
             * Pct Filled
             * @description Fração da reserva-alvo já preenchida (0..1).
             */
            pct_filled: number;
            /**
             * Directed Now
             * @description Quanto deste aporte vai para a reserva (BRL).
             */
            directed_now: number;
            /**
             * Benchmark Cdi Annual
             * @description CDI anualizado (fração), referência.
             */
            benchmark_cdi_annual?: number | null;
            /**
             * Note
             * @default Complete a reserva/CDI antes da renda variável.
             */
            note: string;
        };
        /**
         * SuggestedBuy
         * @description Quanto comprar de um ativo — com a aritmética completa, auditável.
         */
        SuggestedBuy: {
            /**
             * Target Amount
             * @description Valor-alvo a aportar neste ativo (BRL).
             */
            target_amount: number;
            /**
             * Price
             * @description Cotação usada no cálculo (BRL).
             */
            price?: number | null;
            /**
             * Shares
             * @description Número inteiro de cotas/ações sugerido.
             * @default 0
             */
            shares: number;
            /**
             * Invested Exact
             * @description shares * price — gasto real estimado.
             * @default 0
             */
            invested_exact: number;
            /**
             * Lot Size
             * @description Tamanho do lote considerado.
             * @default 1
             */
            lot_size: number;
            /**
             * Lot Note
             * @description Observação sobre lote/arredondamento.
             */
            lot_note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistAdd */
        WatchlistAdd: {
            /** Ticker */
            ticker: string;
            /** Note */
            note?: string | null;
        };
        /** YocPoint */
        YocPoint: {
            /** Month */
            month: string;
            /** Yoc */
            yoc?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    glossary_api_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_brapi_api_debug_brapi_get: {
        parameters: {
            query?: {
                ticker?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
    universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    asset_api_asset__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_latest_api_plan_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
        };
    };
    plan_history_api_plan_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_preferences_api_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    add_to_watchlist_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_api_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_radar_api_watchlist_radar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarResponse"];
                };
            };
        };
    };
    income_api_income_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeResponse"];
                };
            };
        };
    };
    yoc_history_api_income_yoc__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YocPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fixed_income_summary_api_fixed_income_summary_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixedIncomeSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_fixed_income_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_account_api_fixed_income_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_api_fixed_income_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_fixed_income_accounts__account_id__entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_entry_api_fixed_income_accounts__account_id__entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_api_fixed_income_accounts__account_id__entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_order_api_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
