/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary */
        get: operations["glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/brapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Brapi
         * @description Diagnóstico da conexão com a brapi (status HTTP, token presente, resposta crua).
         *
         *     NÃO expõe o token — só o tamanho. Disponível apenas com DEBUG=true (404 caso contrário),
         *     para não vazar configuração em produção.
         */
        get: operations["debug_brapi_api_debug_brapi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategies */
        get: operations["strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Universe */
        get: operations["universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/asset/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset */
        get: operations["asset_api_asset__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_preferences_get"];
        /** Put Preferences */
        put: operations["put_preferences_api_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_api_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_api_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Income
         * @description Renda passiva atual estimada da carteira (Σ valor × DY), com decomposição por ativo.
         */
        get: operations["income_api_income_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Projection
         * @description Projeção bola de neve (e, opcionalmente, o aporte necessário para uma renda-alvo).
         */
        post: operations["projection_api_income_projection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Allocations */
        Allocations: {
            /**
             * By Class
             * @description Peso por classe (0..1).
             */
            by_class?: {
                [key: string]: number;
            };
            /**
             * By Sector
             * @description Peso por setor (0..1).
             */
            by_sector?: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeAsset */
        IncomeAsset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Value */
            value: number;
            /** Dividend Yield */
            dividend_yield: number;
            /** Annual Income */
            annual_income: number;
        };
        /** IncomeResponse */
        IncomeResponse: {
            /**
             * Annual Income
             * @default 0
             */
            annual_income: number;
            /**
             * Monthly Income
             * @default 0
             */
            monthly_income: number;
            /**
             * Portfolio Yield
             * @default 0
             */
            portfolio_yield: number;
            /**
             * Total Value
             * @default 0
             */
            total_value: number;
            /** By Asset */
            by_asset?: components["schemas"]["IncomeAsset"][];
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** Warnings */
            warnings?: string[];
        };
        /** LoginBody */
        LoginBody: {
            /** Password */
            password: string;
        };
        /**
         * Metric
         * @description Uma sub-métrica do score, com valor cru, normalizado e proveniência.
         *
         *     `available=False` significa que a fonte não tinha o dado; nesse caso o peso é
         *     redistribuído entre as métricas disponíveis (ver services/scoring.py) e
         *     `fallback_used` explica qualquer aproximação aplicada.
         */
        Metric: {
            /**
             * Key
             * @description Identificador da métrica e chave no glossário.
             */
            key: string;
            /**
             * Label
             * @description Rótulo curto para a UI (ex: 'P/VP').
             */
            label: string;
            /**
             * Raw Value
             * @description Valor cru, na unidade original.
             */
            raw_value?: number | null;
            /**
             * Display
             * @description Valor já formatado para exibição.
             */
            display?: string | null;
            /**
             * Normalized
             * @description Valor normalizado em [0,1] (maior = melhor).
             */
            normalized?: number | null;
            /**
             * Weight
             * @description Peso desta métrica no score composto (após renormalizar).
             */
            weight: number;
            /**
             * Contribution
             * @description weight * normalized — quanto somou ao score final.
             */
            contribution?: number | null;
            /**
             * Source
             * @description Origem legível do dado.
             */
            source: string;
            /**
             * Available
             * @description False quando a fonte não tinha o dado.
             * @default true
             */
            available: boolean;
            /**
             * Fallback Used
             * @description Aproximação aplicada quando o dado ideal faltava.
             */
            fallback_used?: string | null;
            /**
             * Peer Group
             * @description Grupo de pares usado na normalização (ex: 'FII/Logística').
             */
            peer_group?: string | null;
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Aporte
             * @description Quanto você tem para investir hoje (BRL).
             */
            aporte: number;
            /**
             * Strategy
             * @description Preset de estratégia: 'equilibrado' | 'barsi' | 'bazin' | 'graham'.
             * @default equilibrado
             */
            strategy: string;
            /**
             * Targets
             * @description Alvos de alocação por classe (0..1). Se omitido, usa o default.
             */
            targets?: {
                [key: string]: number;
            } | null;
            /**
             * Weights
             * @description Pesos das famílias de métricas (valuation/dividend/rebalance/sector). Se informado, sobrepõe o preset.
             */
            weights?: {
                [key: string]: number;
            } | null;
            /**
             * Max Assets
             * @description Máximo de ativos diferentes no plano.
             * @default 5
             */
            max_assets: number;
            /**
             * Max Weight Per Asset
             * @description Teto do peso de um ativo na carteira resultante.
             * @default 0.2
             */
            max_weight_per_asset: number;
            /**
             * Min Ticket
             * @description Valor mínimo para alocar em um único ativo (BRL).
             * @default 100
             */
            min_ticket: number;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Aporte */
            aporte: number;
            /**
             * Currency
             * @default BRL
             */
            currency: string;
            /** As Of */
            as_of: string;
            /**
             * Weights
             * @description Pesos usados no score (visíveis para a UI).
             */
            weights?: {
                [key: string]: number;
            };
            /** Targets By Class */
            targets_by_class?: {
                [key: string]: number;
            };
            /** Current By Class */
            current_by_class?: {
                [key: string]: number;
            };
            /** Ranking */
            ranking?: components["schemas"]["ScoredAsset"][];
            /**
             * Unallocated
             * @description Sobra do aporte não alocada (BRL).
             * @default 0
             */
            unallocated: number;
            /** Warnings */
            warnings?: string[];
            /**
             * Disclaimer
             * @default Conteúdo educativo. Não é recomendação de investimento. Os dados podem estar defasados; confira antes de operar.
             */
            disclaimer: string;
        };
        /** Portfolio */
        Portfolio: {
            /**
             * Total Value
             * @description Valor total da carteira (BRL).
             */
            total_value: number;
            /**
             * Currency
             * @description Moeda de referência.
             * @default BRL
             */
            currency: string;
            /** Positions */
            positions?: components["schemas"]["Position"][];
            allocations?: components["schemas"]["Allocations"];
            /**
             * As Of
             * @description Carimbo ISO da leitura.
             */
            as_of: string;
            /**
             * Source
             * @description Origem dos dados.
             * @default ghostfolio
             */
            source: string;
            /** Warnings */
            warnings?: string[];
        };
        /** Position */
        Position: {
            /**
             * Ticker
             * @description Símbolo do ativo (ex: 'BBAS3').
             */
            ticker: string;
            /**
             * Name
             * @description Nome do ativo, se disponível.
             */
            name?: string | null;
            /**
             * Asset Class
             * @description STOCK | FII | ETF | BDR | UNKNOWN.
             * @default UNKNOWN
             */
            asset_class: string;
            /**
             * Sector
             * @description Setor, se conhecido.
             */
            sector?: string | null;
            /**
             * Value
             * @description Valor de mercado da posição (BRL).
             */
            value: number;
            /**
             * Weight
             * @description Peso na carteira (0..1).
             */
            weight: number;
            /**
             * Quantity
             * @description Quantidade de cotas/ações.
             */
            quantity?: number | null;
            /**
             * Tags
             * @description Tags do Ghostfolio nesta posição.
             */
            tags?: string[];
            /**
             * Source
             * @description Origem do dado.
             * @default ghostfolio:holdings
             */
            source: string;
        };
        /**
         * PreferencesBody
         * @description Campos opcionais — só os enviados são atualizados (patch).
         */
        PreferencesBody: {
            /** Strategy */
            strategy?: string | null;
            /** Aporte Default */
            aporte_default?: number | null;
            /** Targets */
            targets?: {
                [key: string]: unknown;
            } | null;
            /** Weights */
            weights?: {
                [key: string]: unknown;
            } | null;
            /** Max Assets */
            max_assets?: number | null;
            /** Max Weight Per Asset */
            max_weight_per_asset?: number | null;
            /** Min Ticket */
            min_ticket?: number | null;
            /** Lot Mode */
            lot_mode?: string | null;
            /** Reserve Target */
            reserve_target?: number | null;
            /** Bazin Target Mode */
            bazin_target_mode?: string | null;
        };
        /** ProjectionPoint */
        ProjectionPoint: {
            /** Year */
            year: number;
            /** Value */
            value: number;
            /** Invested */
            invested: number;
            /** Annual Income */
            annual_income: number;
            /** Monthly Income */
            monthly_income: number;
        };
        /** ProjectionRequest */
        ProjectionRequest: {
            /**
             * Current Value
             * @default 0
             */
            current_value: number;
            /**
             * Monthly Contribution
             * @default 0
             */
            monthly_contribution: number;
            /**
             * Annual Yield
             * @description DY anual em fração (0..1).
             */
            annual_yield: number;
            /**
             * Annual Growth
             * @description Crescimento anual dos proventos (0..1).
             * @default 0
             */
            annual_growth: number;
            /**
             * Years
             * @default 20
             */
            years: number;
            /**
             * Reinvest
             * @default true
             */
            reinvest: boolean;
            /**
             * Target Monthly Income
             * @description Se informado, calcula o aporte mensal necessário para essa renda.
             */
            target_monthly_income?: number | null;
        };
        /** ProjectionResponse */
        ProjectionResponse: {
            /** Series */
            series?: components["schemas"]["ProjectionPoint"][];
            /**
             * Final Value
             * @default 0
             */
            final_value: number;
            /**
             * Final Monthly Income
             * @default 0
             */
            final_monthly_income: number;
            /**
             * Total Invested
             * @default 0
             */
            total_invested: number;
            /**
             * Total Dividends
             * @default 0
             */
            total_dividends: number;
            /** Required Monthly Contribution */
            required_monthly_contribution?: number | null;
        };
        /** ScoredAsset */
        ScoredAsset: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /**
             * Asset Class
             * @default UNKNOWN
             */
            asset_class: string;
            /** Sector */
            sector?: string | null;
            /**
             * Rank
             * @default 0
             */
            rank: number;
            /**
             * Composite Score
             * @description Score final (0..1), média ponderada das métricas.
             */
            composite_score: number;
            /** Metrics */
            metrics?: components["schemas"]["Metric"][];
            /**
             * Data Completeness
             * @description Métricas disponíveis vs totais, ex: '3/4'.
             * @default 0/0
             */
            data_completeness: string;
            suggested?: components["schemas"]["SuggestedBuy"] | null;
            /**
             * Reasons
             * @description Frases curtas explicando por que o ativo subiu no ranking.
             */
            reasons?: string[];
            /**
             * Composite Base
             * @description Score antes do fator de qualidade/risco (auditoria).
             * @default 0
             */
            composite_base: number;
            /**
             * Quality Factor
             * @description Fator de qualidade/risco em [0,1] que multiplica o score (1 = sem penalidade).
             * @default 1
             */
            quality_factor: number;
            /**
             * Risk Level
             * @description Selo de risco: verde | amarelo | vermelho.
             * @default verde
             */
            risk_level: string;
            /**
             * Red Flags
             * @description Pontos de atenção (por que NÃO comprar).
             */
            red_flags?: string[];
        };
        /**
         * SuggestedBuy
         * @description Quanto comprar de um ativo — com a aritmética completa, auditável.
         */
        SuggestedBuy: {
            /**
             * Target Amount
             * @description Valor-alvo a aportar neste ativo (BRL).
             */
            target_amount: number;
            /**
             * Price
             * @description Cotação usada no cálculo (BRL).
             */
            price?: number | null;
            /**
             * Shares
             * @description Número inteiro de cotas/ações sugerido.
             * @default 0
             */
            shares: number;
            /**
             * Invested Exact
             * @description shares * price — gasto real estimado.
             * @default 0
             */
            invested_exact: number;
            /**
             * Lot Size
             * @description Tamanho do lote considerado.
             * @default 1
             */
            lot_size: number;
            /**
             * Lot Note
             * @description Observação sobre lote/arredondamento.
             */
            lot_note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistAdd */
        WatchlistAdd: {
            /** Ticker */
            ticker: string;
            /** Note */
            note?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    glossary_api_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_brapi_api_debug_brapi_get: {
        parameters: {
            query?: {
                ticker?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
    universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    asset_api_asset__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    put_preferences_api_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    add_to_watchlist_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_api_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    income_api_income_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeResponse"];
                };
            };
        };
    };
    projection_api_income_projection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
